Repository tenstorrent/pytorch2.0_ttnn, pull requests merged in 2024-09, with the labels that each got.

#145 Bump metal to latest available wheel build. Fix ttnn.clone usage
  .github/workflows/update-ttnn-wheel.yaml
  requirements.txt
  tools/huggingface_delete_cache.py
  torch_ttnn/backend.py
  torch_ttnn/passes/lowering/target_wrappers.py
Labels: ttnn-wheel-update

#114 Try converting `aten.max_pool2d_with_indices`
  tests/lowering/pool/test_max_pool_2d.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: help wanted

#81 Try converting `floor`
  tests/lowering/eltwise/unary/test_floor.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#180 Refactor manual lowering
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: enhancement, conversion

#137 Model group timm, again, for fixing dependency conflicts among tests.
  requirements-dev.txt
  tests/conftest.py
  tests/models/openpose/test_openpose.py
  tests/models/timm/test_timm_image_classification.py
Labels: model-test

#187 Update TT-NN to 0.52.0-rc20
  requirements.txt
Labels: ttnn-wheel-update

#138 Model YOLOv3.
  .github/actions/common_cleanup/action.yaml
  tests/models/yolov3/holli_src/utils.py
  tests/models/yolov3/holli_src/yolo_layer.py
  tests/models/yolov3/holli_src/yolov3.py
  tests/models/yolov3/holli_src/yolov3_base.py
  tests/models/yolov3/holli_src/yolov3_tiny.py
  tests/models/yolov3/test_yolov3.py
Labels: model-test

#177 Convert `constant_pad_nd` into `ttnn.pad`
  tests/lowering/tensor_manipulation/test_constant_pad_nd.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#142 Model Unet-carvana.
  tests/models/unet_carvana/carvana_unet_segmentation/model.py
  tests/models/unet_carvana/test_unet_carvana.py
Labels: model-test

#139 Add model YOLOv5.
  tests/models/yolov5/test_yolov5.py
Labels: model-test

#189 Convert `aten.repeat` to `ttnn.repeat`
  tests/lowering/tensor_manipulation/test_repeat.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#197 Test yolov5
  tests/models/yolov5/test_yolov5.py
Labels: model-test

#141 Model Pose Landmark.
  README.md
  tests/models/pose_landmark/.gitattributes
  tests/models/pose_landmark/pose_landmarker_lite.task
  tests/models/pose_landmark/test_image.jpg
  tests/models/pose_landmark/test_pose_landmark.py
Labels: model-test

#203 Ignore generated .ttnn_runtime_artifacts
  .gitignore
Labels: enhancement

#205 Model YOLOv5: Clean temporary file by test itself.
  tests/models/yolov5/test_yolov5.py
Labels: enhancement, model-test

#191 Handle `aten._to_copy` op
  tests/lowering/creation/test_to_copy.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/eliminate_coreops_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion, bert

#210 Convert `aten.remainder.Scalar` to `ttnn.remainder`
  tests/lowering/eltwise/unary/test_remainder.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#230 Update TT-NN to 0.52.0-rc27
  requirements.txt
Labels: ttnn-wheel-update

#234 Update TT-NN to 0.52.0-rc28
  requirements.txt
Labels: ttnn-wheel-update

#254 Update TT-NN to 0.52.0-rc30
  requirements.txt
Labels: ttnn-wheel-update

#257 Update TT-NN to 0.52.0-rc31
  requirements.txt
Labels: ttnn-wheel-update

#259 Update TT-NN to 0.52.0-rc32
  requirements.txt
Labels: ttnn-wheel-update

#263 Update TT-NN to 0.52.0-rc33
  requirements.txt
Labels: ttnn-wheel-update

#266 Update TT-NN to 0.52.1-rc1
  requirements.txt
Labels: ttnn-wheel-update

#272 Update TT-NN to 0.53.0-rc2
  requirements.txt
Labels: ttnn-wheel-update

#273 Update TT-NN to 0.53.0-rc3
  requirements.txt
Labels: ttnn-wheel-update
