Repository tenstorrent/pytorch2.0_ttnn, pull requests merged in 2024-10, with the labels that each got.

#171 Model Hand Landmark, with Git LFS.
  tests/models/hand_landmark/.gitattributes
  tests/models/hand_landmark/hand_landmarker.task
  tests/models/hand_landmark/test_hand_landmark.py
  tests/models/hand_landmark/woman_hands.jpg
Labels: model-test

#275 Update TT-NN to 0.53.0-rc4
  requirements.txt
Labels: ttnn-wheel-update

#277 Update TT-NN to 0.53.0-rc5
  requirements.txt
Labels: ttnn-wheel-update

#278 Update TT-NN to 0.53.0-rc6
  requirements.txt
Labels: ttnn-wheel-update

#287 Update TT-NN to 0.53.0-rc8
  requirements.txt
Labels: ttnn-wheel-update

#297 Update TT-NN to 0.53.0-rc9
  requirements.txt
Labels: ttnn-wheel-update

#299 Update TT-NN to 0.53.0-rc10
  requirements.txt
Labels: ttnn-wheel-update

#279 Enable more numerical stability for `ttnn.softmax`
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#301 Update TT-NN to 0.53.0-rc11
  requirements.txt
Labels: ttnn-wheel-update

#274 Apply model tester
  tests/conftest.py
  tests/models/MobileNetV2/test_MobileNetV2.py
  tests/models/albert/test_albert_masked_lm.py
  tests/models/albert/test_albert_question_answering.py
  tests/models/albert/test_albert_sequence_classification.py
  tests/models/albert/test_albert_token_classification.py
  tests/models/autoencoder_conv/test_autoencoder_conv.py
  tests/models/autoencoder_conv/test_autoencoder_conv_v2.py
  tests/models/autoencoder_linear/test_autoencoder_linear.py
  tests/models/beit/test_beit_image_classification.py
  tests/models/bert/test_bert.py
  tests/models/bloom/test_bloom.py
  tests/models/clip/test_clip.py
  tests/models/codegen/test_codegen.py
  tests/models/deit/test_deit.py
  tests/models/detr/test_detr.py
  tests/models/distilbert/test_distilbert.py
  tests/models/dpr/test_dpr.py
  tests/models/falcon/test_falcon.py
  tests/models/flan_t5/test_flan_t5.py
  tests/models/glpn_kitti/test_glpn_kitti.py
  tests/models/gpt2/test_gpt2.py
  tests/models/gpt_neo/test_gpt_neo.py
  tests/models/hand_landmark/test_hand_landmark.py
  tests/models/hardnet/test_hardnet.py
  tests/models/llama/test_llama.py
  tests/models/mlpmixer/test_mlpmixer.py
  tests/models/mnist/test_mnist.py
  tests/models/mobilenet_ssd/test_mobilenet_ssd.py
  tests/models/musicgen_small/test_musicgen_small.py
  tests/models/openpose/test_openpose.py
  tests/models/openpose/test_openpose_v2.py
  tests/models/opt/test_opt.py
  tests/models/perceiver_io/test_perceiver_io.py
  tests/models/resnet/test_resnet.py
  tests/models/resnet50/test_resnet50.py
  tests/models/roberta/test_roberta.py
  tests/models/segformer/test_segformer.py
  tests/models/segment_anything/test_segment_anything.py
  tests/models/speecht5_tts/test_speecht5_tts.py
  tests/models/squeeze_bert/test_squeeze_bert.py
  tests/models/stable_diffusion/test_stable_diffusion.py
  tests/models/stable_diffusion/test_stable_diffusion_v2.py
  tests/models/t5/test_t5.py
  tests/models/timm/test_timm_image_classification.py
  tests/models/torchvision/test_torchvision_image_classification.py
  tests/models/torchvision/test_torchvision_object_detection.py
  tests/models/unet/test_unet.py
  tests/models/unet_brain/test_unet_brain.py
  tests/models/unet_carvana/test_unet_carvana.py
  tests/models/vilt/test_vilt.py
  tests/models/whisper/test_whisper.py
  tests/models/xglm/test_xglm.py
  tests/models/yolos/test_yolos.py
  tests/models/yolov3/test_yolov3.py
  tests/models/yolov5/test_yolov5.py
  tests/utils.py
Labels: training

#307 Update TT-NN to 0.53.0-rc12
  requirements.txt
Labels: ttnn-wheel-update

#309 Update TT-NN to 0.53.0-rc13
  requirements.txt
Labels: ttnn-wheel-update

#312 Update TT-NN to 0.53.0-rc14
  requirements.txt
Labels: ttnn-wheel-update

#281 Training test autoencoder conv
  tests/models/autoencoder_conv/test_autoencoder_conv.py
  tests/models/autoencoder_conv/test_autoencoder_conv_v2.py
Labels: training

#283 Training test beit
  tests/models/beit/test_beit_image_classification.py
Labels: training

#284 Training test clip
  tests/models/clip/test_clip.py
Labels: training

#285 Training test deit
  tests/models/deit/test_deit.py
Labels: training

#286 Training test hardnet
  tests/models/hardnet/test_hardnet.py
Labels: training

#289 Training test openpose
  tests/models/openpose/test_openpose.py
  tests/models/openpose/test_openpose_v2.py
Labels: training

#290 Training test resnet
  tests/models/resnet/test_resnet.py
  tests/models/resnet50/test_resnet50.py
Labels: training

#291 Training test segformer
  tests/models/segformer/test_segformer.py
Labels: training

#292 Training test timm
  tests/models/timm/test_timm_image_classification.py
Labels: training

#293 Training test unet
  tests/models/unet/test_unet.py
Labels: training

#294 Training test unet brain
  tests/models/unet_brain/test_unet_brain.py
Labels: training

#314 Update TT-NN to 0.53.0-rc16
  requirements.txt
Labels: ttnn-wheel-update

#327 Update TT-NN to 0.53.0-rc21
  requirements.txt
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: ttnn-wheel-update

#339 Update TT-NN to 0.53.0-rc25
  requirements.txt
Labels: ttnn-wheel-update

#349 Update TT-NN to 0.53.0-rc27
  requirements.txt
Labels: ttnn-wheel-update

#355 Update TT-NN to 0.53.0-rc28
  requirements.txt
Labels: ttnn-wheel-update
