Repository tenstorrent/pytorch2.0_ttnn, pull requests merged in 2024-12, with the labels that each got.

#526 Update TT-NN to 0.53.1-rc4
  requirements.txt
  tests/lowering/eltwise/binary/test_sub.py
  torch_ttnn/passes/lowering/to_tt_guard_autogen.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: ttnn-wheel-update

#549 Update TT-NN to 0.53.1-rc8
  requirements.txt
Labels: ttnn-wheel-update

#553 Update TT-NN to 0.53.1-rc9
  requirements.txt
Labels: ttnn-wheel-update

#558 Update TT-NN to 0.53.1-rc11
  requirements.txt
Labels: ttnn-wheel-update

#563 Update TT-NN to 0.53.1-rc13
  requirements.txt
Labels: ttnn-wheel-update

#567 Update TT-NN to 0.53.1-rc14
  requirements.txt
Labels: ttnn-wheel-update

#575 Update TT-NN to 0.53.1-rc15
  requirements.txt
Labels: ttnn-wheel-update

#607 Update TT-NN to 0.53.1-rc23
  requirements.txt
Labels: ttnn-wheel-update

#609 Update TT-NN to 0.53.1-rc25
  requirements.txt
Labels: ttnn-wheel-update

#622 Update TT-NN to 0.54.0-rc1
  requirements.txt
Labels: ttnn-wheel-update

#378 Optimize out `aten.detach`
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#236 Convert `aten.bitwise_not` to `ttnn.bitwise_not`
  tests/lowering/eltwise/unary/test_bitwise_not.py
  torch_ttnn/backend.py
  torch_ttnn/passes/lowering/add_data_move_pass.py
  torch_ttnn/passes/lowering/to_tt_pass.py
  torch_ttnn/utils.py
Labels: blocked, conversion

#674 Update TT-NN to 0.54.0-rc6
  requirements.txt
Labels: ttnn-wheel-update

#670 Lower `aten.as_strided` when it can be simplified into `ttnn.reshape`
  tests/lowering/tensor_manipulation/test_as_strided.py
  torch_ttnn/passes/lowering/to_tt_pass.py
Labels: conversion

#680 Update TT-NN to 0.54.0-rc7
  requirements.txt
Labels: ttnn-wheel-update

#681 Update TT-NN to 0.54.0-rc8
  requirements.txt
Labels: ttnn-wheel-update

#684 Update TT-NN to 0.54.0-rc9
  requirements.txt
Labels: ttnn-wheel-update

#687 Update TT-NN to 0.54.0-rc10
  requirements.txt
Labels: ttnn-wheel-update

#691 Update TT-NN to 0.54.0-rc11
  requirements.txt
Labels: ttnn-wheel-update
